# Generated by Django 6.0.3 on 2026-04-26 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('KGS', 'KGS'), ('USD', 'USD'), ('EUR', 'EUR')], default='KGS', max_length=3)),
                ('pricing_source', models.CharField(choices=[('manual', 'Manual'), ('promotion', 'Promotion'), ('import', 'Import')], db_index=True, default='manual', max_length=16)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_prices', to='screenings.moviesession')),
            ],
            options={
                'ordering': ['session_id', 'currency'],
                'indexes': [models.Index(fields=['session', 'currency'], name='pricing_session_currency_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='pricing_amount_gt_zero'), models.UniqueConstraint(fields=('session', 'currency'), name='pricing_unique_session_currency')],
            },
        ),
    ]
