# Generated by Django 6.0.3 on 2026-04-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('sci_fi', 'Sci-Fi'), ('thriller', 'Thriller'), ('animation', 'Animation')], db_index=True, max_length=32)),
                ('duration', models.PositiveSmallIntegerField(help_text='Duration in minutes.')),
                ('age_rating', models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], db_index=True, max_length=3)),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('release_date', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['is_active', 'release_date'], name='movies_active_release_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration__gt', 0)), name='movies_movie_duration_gt_zero')],
            },
        ),
    ]
