# Generated by Django 6.0.3 on 2026-04-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rows', models.PositiveSmallIntegerField()),
                ('seats_per_row', models.PositiveSmallIntegerField()),
                ('schema_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['rows', 'seats_per_row'], name='halls_capacity_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rows__gt', 0)), name='halls_rows_gt_zero'), models.CheckConstraint(condition=models.Q(('seats_per_row__gt', 0)), name='halls_seats_per_row_gt_zero')],
            },
        ),
    ]
