# Generated by Django 6.0.3 on 2026-04-26 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halls', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='halls.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='movies.movie')),
            ],
            options={
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['movie', 'start_datetime'], name='screenings_movie_start_idx'), models.Index(fields=['hall', 'start_datetime'], name='screenings_hall_start_idx'), models.Index(fields=['is_active', 'start_datetime'], name='screenings_active_start_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='screenings_end_after_start'), models.UniqueConstraint(fields=('hall', 'start_datetime'), name='screenings_unique_hall_start')],
            },
        ),
    ]
