# Generated by Django 6.0.3 on 2026-04-26 06:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screenings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('booking_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='screenings.moviesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_row', models.PositiveSmallIntegerField()),
                ('seat_number', models.PositiveSmallIntegerField()),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.booking')),
            ],
            options={
                'ordering': ['seat_row', 'seat_number'],
            },
        ),
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_row', models.PositiveSmallIntegerField()),
                ('seat_number', models.PositiveSmallIntegerField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('held', 'Held'), ('booked', 'Booked'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='held', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='screenings.moviesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expires_at', 'seat_row', 'seat_number'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'booking_status'], name='bookings_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['session', 'booking_status'], name='bookings_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status', 'created_at'], name='bookings_payment_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('0.00'))), name='bookings_total_amount_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='bookingseat',
            index=models.Index(fields=['seat_row', 'seat_number'], name='bookings_seat_coordinates_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.CheckConstraint(condition=models.Q(('seat_row__gt', 0)), name='bookings_seat_row_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.CheckConstraint(condition=models.Q(('seat_number__gt', 0)), name='bookings_seat_number_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.CheckConstraint(condition=models.Q(('price_at_booking__gte', Decimal('0.00'))), name='bookings_seat_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.UniqueConstraint(fields=('booking', 'seat_row', 'seat_number'), name='bookings_unique_booking_seat'),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['session', 'status'], name='bk_hold_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['session', 'expires_at'], name='bk_hold_session_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['user', 'status'], name='bookings_hold_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='seathold',
            constraint=models.CheckConstraint(condition=models.Q(('seat_row__gt', 0)), name='bookings_hold_row_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='seathold',
            constraint=models.CheckConstraint(condition=models.Q(('seat_number__gt', 0)), name='bookings_hold_seat_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='seathold',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'held')), fields=('session', 'seat_row', 'seat_number'), name='bookings_unique_active_hold_seat'),
        ),
        migrations.AddConstraint(
            model_name='seathold',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('session', 'seat_row', 'seat_number'), name='bookings_unique_booked_hold_seat'),
        ),
    ]
