# Generated by Django 6.0.3 on 2026-04-27 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('screenings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(choices=[('KGS', 'KGS'), ('USD', 'USD'), ('EUR', 'EUR')], default='KGS', max_length=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='seathold',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='bookings.booking'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_status', 'expires_at'], name='bookings_status_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['booking', 'status'], name='bk_hold_booking_status_idx'),
        ),
    ]
